In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\application\storage\data_ingestion\2022-10-28-01-23-59\raw_data\Kaggle_Test_Dataset_v2.csv")

C:\Users\kanan\AppData\Local\Temp\ipykernel_13520\590950053.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\application\storage\data_ingestion\2022-10-28-01-23-59\raw_data\Kaggle_Test_Dataset_v2.csv")

In [3]:
df.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,3285085,62.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
1,3285131,9.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,No,No,Yes,No,No,No
2,3285358,17.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.92,0.95,0.0,No,No,No,Yes,No,No
3,3285517,9.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.78,0.75,0.0,No,No,Yes,Yes,No,No
4,3285608,2.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.54,0.71,0.0,No,No,No,Yes,No,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242076 entries, 0 to 242075
Data columns (total 23 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   sku                242076 non-null  object
 1   national_inv       242075 non-null  float64
 2   lead_time          227351 non-null  float64
 3   in_transit_qty     242075 non-null  float64
 4   forecast_3_month   242075 non-null  float64
 5   forecast_6_month   242075 non-null  float64
 6   forecast_9_month   242075 non-null  float64
 7   sales_1_month      242075 non-null  float64
 8   sales_3_month      242075 non-null  float64
 9   sales_6_month      242075 non-null  float64
 10  sales_9_month      242075 non-null  float64
 11  min_bank           242075 non-null  float64
 12  potential_issue    242075 non-null  object
 13  pieces_past_due    242075 non-null  float64
 14  perf_6_month_avg   242075 non-null  float64
 15  perf_12_month_avg  242075 non-null  float64
 16  local_bo_qty       242075 non-null  float64
 17  deck_risk          242075 non-null  object
 18  oe_constraint      242075 non-null  object
 19  ppap_risk          242075 non-null  object
 20  stop_auto_buy      242075 non-null  object
 21  rev_stop           242075 non-null  object
 22  went_on_backorder  242075 non-null  object
dtypes: float64(15), object(8)
memory usage: 42.5+ MB

In [5]:
train = pd.read_csv(r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\application\storage\data_ingestion\2022-10-28-01-23-59\raw_data\Kaggle_Training_Dataset_v2.csv")

C:\Users\kanan\AppData\Local\Temp\ipykernel_13520\739955797.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv(r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\application\storage\data_ingestion\2022-10-28-01-23-59\raw_data\Kaggle_Training_Dataset_v2.csv")

In [6]:
train.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,1043384,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,1043696,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,1043852,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,1044048,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1687861 entries, 0 to 1687860
Data columns (total 23 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   sku                1687861 non-null  object
 1   national_inv       1687860 non-null  float64
 2   lead_time          1586967 non-null  float64
 3   in_transit_qty     1687860 non-null  float64
 4   forecast_3_month   1687860 non-null  float64
 5   forecast_6_month   1687860 non-null  float64
 6   forecast_9_month   1687860 non-null  float64
 7   sales_1_month      1687860 non-null  float64
 8   sales_3_month      1687860 non-null  float64
 9   sales_6_month      1687860 non-null  float64
 10  sales_9_month      1687860 non-null  float64
 11  min_bank           1687860 non-null  float64
 12  potential_issue    1687860 non-null  object
 13  pieces_past_due    1687860 non-null  float64
 14  perf_6_month_avg   1687860 non-null  float64
 15  perf_12_month_avg  1687860 non-null  float64
 16  local_bo_qty       1687860 non-null  float64
 17  deck_risk          1687860 non-null  object
 18  oe_constraint      1687860 non-null  object
 19  ppap_risk          1687860 non-null  object
 20  stop_auto_buy      1687860 non-null  object
 21  rev_stop           1687860 non-null  object
 22  went_on_backorder  1687860 non-null  object
dtypes: float64(15), object(8)
memory usage: 296.2+ MB

In [8]:
for col in train.columns:
    print(col,": ",train[col].dtype)

sku :  object
national_inv :  float64
lead_time :  float64
in_transit_qty :  float64
forecast_3_month :  float64
forecast_6_month :  float64
forecast_9_month :  float64
sales_1_month :  float64
sales_3_month :  float64
sales_6_month :  float64
sales_9_month :  float64
min_bank :  float64
potential_issue :  object
pieces_past_due :  float64
perf_6_month_avg :  float64
perf_12_month_avg :  float64
local_bo_qty :  float64
deck_risk :  object
oe_constraint :  object
ppap_risk :  object
stop_auto_buy :  object
rev_stop :  object
went_on_backorder :  object

In [9]:
num = []
cat = []
for col in train.columns:
    if train[col].dtype == 'float':
        num.append(col)
    else:
        cat.append(col)

In [14]:
for i in cat:
    print(i,train[i].unique())

sku [1026827 1043384 1043696 ... '1439563' '1502009' '(1687860 rows)']
potential_issue ['No' 'Yes' nan]
deck_risk ['No' 'Yes' nan]
oe_constraint ['No' 'Yes' nan]
ppap_risk ['No' 'Yes' nan]
stop_auto_buy ['Yes' 'No' nan]
rev_stop ['No' 'Yes' nan]
went_on_backorder ['No' 'Yes' nan]

In [ ]:
for i

In [12]:
import pandas as pd
import os
from shutil import copy
raw_data_dir= r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\application\storage\data_ingestion\2022-10-28-14-42-40\raw_data"
src_directory = r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\application\storage\data_ingestion\2022-10-28-14-42-40\raw_data\Kaggle_Training_Dataset_v2.csv"
dest_directory = r"D:\ineuron\Backorder_Prediction_Project\Backorder_Prediction\notebook"

In [19]:
for filename in os.listdir(raw_data_dir):
    src_file = os.path.join(raw_data_dir,filename)

    if filename == "Kaggle_Training_Dataset_v2.csv":
                    dest_file = os.path.join(dest_directory,filename)
                    os.makedirs(dest_file,exist_ok=True)
                    copy(src_file,dest_file)